/**
 * TourEngine — guided, narrated walkthrough of the v3 console.
 *
 * Drives the REAL UI through the hooks defined in tourSteps.js: a spotlight
 * hole (box-shadow trick) travels between targets while a card explains the
 * step and a pre-generated MP3 narrates it (static files in /v3/assets/tour/,
 * generated by v3/tools/gen-tour-audio.mjs — no runtime AI dependency, the
 * demo must never break).
 *
 * Modes: manual (Back/Next/keyboard), chapter jumps, auto-play (advances when
 * the narration ends — presentation mode). First visit auto-launches once
 * (localStorage v3_tour_seen).
 */

import { TOUR_STEPS } from './tourSteps.js';

const AUDIO_BASE = '/v3/assets/tour/';
const AUDIO_VERSION = 'v=5';   // bump after regenerating narration (gen-tour-audio.mjs)
const SEEN_KEY = 'v3_tour_seen';
const MUTE_KEY = 'v3_tour_muted';
const AUTOPLAY_FALLBACK_MS = 9000;   // no/failed audio → advance after this in auto-play

export class TourEngine {
    constructor(app) {
        this.app = app;
        this.steps = TOUR_STEPS;
        this.chapters = [...new Set(this.steps.map(s => s.chapter))];
        this.index = -1;
        this.active = false;
        // The tour is a narrated presentation: it PLAYS by default (narration
        // + auto-advance when each step's audio ends). The ▶/⏸ button pauses
        // and resumes that — a real media control, not an opt-in toggle.
        this.paused = false;
        this.muted = localStorage.getItem(MUTE_KEY) === '1';
        this.audio = null;
        this.autoTimer = null;
        this.repositionTimers = [];
        this._buildDom();
        window.addEventListener('resize', () => this.active && this._position());
        document.addEventListener('keydown', (e) => {
            if (!this.active) return;
            if (e.key === 'ArrowRight') { e.preventDefault(); this.next(); }
            else if (e.key === 'ArrowLeft') { e.preventDefault(); this.prev(); }
            else if (e.key === 'Escape') { e.preventDefault(); this.end(); }
        });
    }

    // ---------- DOM ----------

    _buildDom() {
        this.hole = document.createElement('div');
        this.hole.className = 'tour-hole';
        this.hole.hidden = true;

        this.card = document.createElement('div');
        this.card.className = 'tour-card';
        this.card.hidden = true;
        this.card.innerHTML = `
            <div class="tour-card-top">
                <select class="tour-chapters" title="Jump to chapter"></select>
                <span class="tour-progress"></span>
                <span class="tour-top-spacer"></span>
                <button class="tour-icon-btn tour-mute" title="Toggle narration"></button>
                <button class="tour-icon-btn tour-auto" title="Pause / resume the narration"></button>
                <button class="tour-icon-btn tour-close" title="End tour (Esc)">×</button>
            </div>
            <div class="tour-title"></div>
            <div class="tour-body"></div>
            <div class="tour-audio-note" hidden>⏸ Paused — click anywhere or press ▶ to start the narration.</div>
            <div class="tour-card-controls">
                <button class="tour-btn tour-back">◀ Back</button>
                <button class="tour-btn tour-skip">Skip tour</button>
                <button class="tour-btn tour-primary tour-next">Next ▶</button>
            </div>`;

        const chapSel = this.card.querySelector('.tour-chapters');
        for (const c of this.chapters) {
            const o = document.createElement('option');
            o.value = c; o.textContent = c;
            chapSel.appendChild(o);
        }
        chapSel.addEventListener('change', () => {
            const first = this.steps.findIndex(s => s.chapter === chapSel.value);
            if (first >= 0) this.goTo(first);
        });

        this.card.querySelector('.tour-next').addEventListener('click', () => this.next());
        this.card.querySelector('.tour-back').addEventListener('click', () => this.prev());
        this.card.querySelector('.tour-skip').addEventListener('click', () => this.end());
        this.card.querySelector('.tour-close').addEventListener('click', () => this.end());
        this.card.querySelector('.tour-mute').addEventListener('click', () => this.toggleMute());
        this.card.querySelector('.tour-auto').addEventListener('click', () => this.togglePause());

        document.body.appendChild(this.hole);
        document.body.appendChild(this.card);
        this._syncToggleButtons();
    }

    _syncToggleButtons() {
        const mute = this.card.querySelector('.tour-mute');
        mute.textContent = this.muted ? '🔇' : '🔊';
        mute.classList.toggle('tour-toggle-on', !this.muted);
        const auto = this.card.querySelector('.tour-auto');
        auto.textContent = this.paused ? '▶' : '⏸';
        auto.title = this.paused ? 'Resume the narration' : 'Pause the narration';
        auto.classList.toggle('tour-toggle-on', !this.paused);
    }

    // ---------- lifecycle ----------

    start(at = 0) {
        this.active = true;
        this.hole.hidden = false;
        this.card.hidden = false;
        this.goTo(at);
    }

    end() {
        this.active = false;
        this.index = -1;
        this.paused = false;
        this.hole.hidden = true;
        this.card.hidden = true;
        this._stopAudio();
        this._clearTimers();
        localStorage.setItem(SEEN_KEY, '1');
        try {
            // leave the console in a sane default state
            const sel = document.getElementById('persona-select');
            if (sel && sel.value !== 'PI') {
                sel.value = 'PI';
                sel.dispatchEvent(new Event('change', { bubbles: true }));
            }
        } catch { /* never break the app on tour teardown */ }
    }

    async goTo(i) {
        if (i < 0 || i >= this.steps.length) { this.end(); return; }
        this._stopAudio();
        this._clearTimers();
        this.paused = false;            // navigating always plays the destination step
        this._syncToggleButtons();
        this.index = i;
        const step = this.steps[i];

        try { await step.before?.(this.app); } catch (e) { console.warn('tour before() failed:', e); }

        this._renderCard(step);
        this._position();
        // panels/map settle with transitions — re-measure a few times
        for (const ms of [300, 700, 1300]) {
            this.repositionTimers.push(setTimeout(() => this.active && this._position(), ms));
        }
        this._playAudio(step);
    }

    next() { this.goTo(this.index + 1); }
    prev() { this.goTo(this.index - 1); }

    // ---------- rendering ----------

    _renderCard(step) {
        this.card.querySelector('.tour-chapters').value = step.chapter;
        this.card.querySelector('.tour-progress').textContent =
            `${this.index + 1}/${this.steps.length}`;
        this.card.querySelector('.tour-title').textContent = step.title;
        this.card.querySelector('.tour-body').innerHTML = step.html;
        this.card.querySelector('.tour-audio-note').hidden = true;
        this.card.querySelector('.tour-back').disabled = this.index === 0;
        this.card.querySelector('.tour-next').textContent =
            this.index === this.steps.length - 1 ? 'Finish ✓' : 'Next ▶';
    }

    _targetRect(target) {
        const sels = Array.isArray(target) ? target : [target];
        let r = null;
        for (const sel of sels) {
            const el = document.querySelector(sel);
            if (!el) continue;
            const b = el.getBoundingClientRect();
            if (b.width === 0 && b.height === 0) continue;
            r = r ? {
                left: Math.min(r.left, b.left), top: Math.min(r.top, b.top),
                right: Math.max(r.right, b.right), bottom: Math.max(r.bottom, b.bottom)
            } : { left: b.left, top: b.top, right: b.right, bottom: b.bottom };
        }
        return r;
    }

    _position() {
        const step = this.steps[this.index];
        if (!step) return;
        const pad = 6;
        const r = step.target ? this._targetRect(step.target) : null;

        if (r) {
            this.hole.style.opacity = '1';
            this.hole.style.left = (r.left - pad) + 'px';
            this.hole.style.top = (r.top - pad) + 'px';
            this.hole.style.width = (r.right - r.left + 2 * pad) + 'px';
            this.hole.style.height = (r.bottom - r.top + 2 * pad) + 'px';
        } else {
            // no target: shade everything, hole collapsed off-screen
            this.hole.style.opacity = '1';
            this.hole.style.left = '50%';
            this.hole.style.top = '-20px';
            this.hole.style.width = '0px';
            this.hole.style.height = '0px';
        }

        // card placement: right → left → below → above → center
        const cw = 380, margin = 14;
        const ch = this.card.offsetHeight || 320;
        const vw = window.innerWidth, vh = window.innerHeight;
        let x, y;
        if (!r) {
            x = (vw - cw) / 2; y = (vh - ch) / 2;
        } else if (r.right + margin + cw < vw) {
            x = r.right + margin; y = r.top;
        } else if (r.left - margin - cw > 0) {
            x = r.left - margin - cw; y = r.top;
        } else if (r.bottom + margin + ch < vh) {
            x = Math.min(Math.max(r.left, margin), vw - cw - margin); y = r.bottom + margin;
        } else if (r.top - margin - ch > 0) {
            x = Math.min(Math.max(r.left, margin), vw - cw - margin); y = r.top - margin - ch;
        } else {
            x = (vw - cw) / 2; y = (vh - ch) / 2;
        }
        this.card.style.left = Math.round(Math.min(Math.max(x, margin), vw - cw - margin)) + 'px';
        this.card.style.top = Math.round(Math.min(Math.max(y, margin), vh - ch - margin)) + 'px';
    }

    // ---------- audio ----------

    _playAudio(step) {
        if (this.muted) { this._armAutoAdvance(AUTOPLAY_FALLBACK_MS); return; }
        const a = new Audio(`${AUDIO_BASE}${step.id}.mp3?${AUDIO_VERSION}`);
        this.audio = a;
        // Guard every handler on audio identity: once we move on, `this.audio`
        // is a different element (or null), so a stale event — including the
        // 'error' that _stopAudio's teardown fires — becomes a no-op and can
        // never arm the auto-advance for the wrong step.
        const onEnded = () => { if (a === this.audio) this._armAutoAdvance(900); };
        const onError = () => { if (a === this.audio) this._armAutoAdvance(AUTOPLAY_FALLBACK_MS); };
        a.addEventListener('ended', onEnded);
        a.addEventListener('error', onError);
        a._cleanup = () => {
            a.removeEventListener('ended', onEnded);
            a.removeEventListener('error', onError);
        };
        a.play().catch(() => {
            // Autoplay policy: no user gesture yet. HOLD the tour (paused) so it
            // doesn't fly through steps silently; the first interaction resumes.
            if (a !== this.audio) return;
            this.paused = true;
            this._syncToggleButtons();
            const note = this.card.querySelector('.tour-audio-note');
            note.hidden = false;
            const resume = () => {
                document.removeEventListener('pointerdown', resume, true);
                note.hidden = true;
                if (this.audio === a && this.active && this.paused) {
                    this.paused = false;
                    this._syncToggleButtons();
                    a.play().catch(() => {});
                }
            };
            document.addEventListener('pointerdown', resume, true);
        });
    }

    _stopAudio() {
        if (this.audio) {
            const a = this.audio;
            this.audio = null;          // null FIRST: any late event now fails the identity guard
            a._cleanup?.();             // drop listeners before teardown can fire 'error'
            a.pause();
            a.removeAttribute('src');
            a.load?.();                 // release the buffer without a handled error
        }
    }

    _armAutoAdvance(delayMs) {
        if (this.paused || !this.active) return;
        clearTimeout(this.autoTimer);
        this.autoTimer = setTimeout(() => {
            if (!this.paused && this.active) this.next();
        }, delayMs);
    }

    _clearTimers() {
        clearTimeout(this.autoTimer);
        this.autoTimer = null;
        this.repositionTimers.forEach(clearTimeout);
        this.repositionTimers = [];
    }

    // ---------- toggles ----------

    toggleMute() {
        this.muted = !this.muted;
        localStorage.setItem(MUTE_KEY, this.muted ? '1' : '0');
        this._syncToggleButtons();
        if (this.muted) this._stopAudio();
        else if (this.active && !this.paused) this._playAudio(this.steps[this.index]);
    }

    /** ▶/⏸ — pause or resume the narration (and the auto-advance with it). */
    togglePause() {
        this.paused = !this.paused;
        this._syncToggleButtons();
        if (this.paused) {
            this.audio?.pause();
            clearTimeout(this.autoTimer);
        } else if (this.audio && !this.audio.ended) {
            this.audio.play().catch(() => {});   // resume from where it stopped
        } else {
            this._armAutoAdvance(600);            // narration already finished → continue the tour
        }
    }
}

/** Wire the tour into the console: toolbar button + first-visit auto-launch. */
export function initTour(app) {
    const tour = new TourEngine(app);

    const btn = document.getElementById('btn-tour');
    btn?.addEventListener('click', () => tour.active ? tour.end() : tour.start(0));

    if (!localStorage.getItem(SEEN_KEY)) {
        setTimeout(() => { if (!tour.active) tour.start(0); }, 3000);
    }
    return tour;
}
